language: minimal 

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t samadarshad/$PROJECT_NAME:${TRAVIS_COMMIT::8} .
  - docker images

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samadarshad/$PROJECT_NAME:${TRAVIS_COMMIT::8}